"use client";

import { useRouter } from "next/navigation";

export default function PrivacyPage() {
  const router = useRouter();

  return (
    <div style={{ background: "var(--page-bg)", minHeight: "100vh", paddingBottom: 80 }}>
      {/* Header */}
      <div style={{ position: "sticky", top: 0, zIndex: 20, background: "var(--page-bg)", borderBottom: "0.5px solid var(--page-border)", padding: "12px 16px", display: "flex", alignItems: "center", gap: 12 }}>
        <button
          onClick={() => router.back()}
          style={{ background: "none", border: "none", cursor: "pointer", padding: 4, display: "flex", alignItems: "center", color: "var(--page-text-primary)" }}
        >
          <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
            <line x1="19" y1="12" x2="5" y2="12" /><polyline points="12 19 5 12 12 5" />
          </svg>
        </button>
        <h1 style={{ fontFamily: "var(--font-body)", fontSize: 16, fontWeight: 600, color: "var(--page-text-primary)", margin: 0 }}>
          Privacy Policy
        </h1>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 680, margin: "0 auto", padding: "24px 20px" }}>

        <p style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--page-text-muted)", letterSpacing: "0.06em", marginBottom: 32 }}>
          Effective Date: July 15, 2025 · Last Updated: July 15, 2025
        </p>

        {/* Section 1 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "0 0 12px", paddingTop: 0, borderTop: "none" }}>
          1. Introduction
        </h2>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          FYTD ("Find Your Fit Daily") is a fashion social platform operated by Devlin, based in Washington State. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our website at fytd.org and any related services. By creating an account or using the Platform you agree to the practices described here.
        </p>

        {/* Section 2 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          2. Information We Collect
        </h2>

        <h3 style={{ fontFamily: "var(--font-body)", fontSize: 14, fontWeight: 600, color: "var(--page-text-primary)", margin: "20px 0 8px", letterSpacing: "0.01em" }}>
          2.1 Information You Provide Directly
        </h3>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>Account Information:</strong> email address, password (encrypted, never stored in plain text), username, display name.
        </p>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>Profile Information:</strong> profile avatar or photo, bio, style tags and preferences, Instagram handle (optional).
        </p>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>Content You Post:</strong> outfit photos and videos, post titles and captions, style tags, fit breakdown data including item names, brand names, categories, prices, shop links, and How I Found It descriptions, comments and replies, GIFs shared in comments.
        </p>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>Social Activity:</strong> posts you like, posts and items you save, accounts you follow, accounts you block or report, direct messages you send and receive, notifications generated by your activity.
        </p>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>Communications:</strong> messages sent through in-app messaging, feedback submitted through our feedback tool.
        </p>

        <h3 style={{ fontFamily: "var(--font-body)", fontSize: 14, fontWeight: 600, color: "var(--page-text-primary)", margin: "20px 0 8px", letterSpacing: "0.01em" }}>
          2.2 Information Collected Automatically
        </h3>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          Browser type and version, device type, operating system, IP address, pages visited and features used, time and date of visit, referring URLs. Used to maintain and improve the Platform.
        </p>

        <h3 style={{ fontFamily: "var(--font-body)", fontSize: 14, fontWeight: 600, color: "var(--page-text-primary)", margin: "20px 0 8px", letterSpacing: "0.01em" }}>
          2.3 Information from Third-Party Services
        </h3>
        <ul style={{ margin: "8px 0 16px", paddingLeft: 20 }}>
          {[
            { name: "Supabase", desc: "database and authentication provider. SOC 2 compliant.", url: "https://supabase.com/privacy", label: "supabase.com/privacy" },
            { name: "Vercel", desc: "hosting provider.", url: "https://vercel.com/legal/privacy-policy", label: "vercel.com/legal/privacy-policy" },
            { name: "Resend", desc: "email delivery for confirmation and password reset emails.", url: "https://resend.com/legal/privacy-policy", label: "resend.com/legal/privacy-policy" },
            { name: "Anthropic (Claude API)", desc: "AI-assisted fit breakdown feature. Photos and URLs submitted for analysis are processed by Anthropic's API. Anthropic does not use API inputs to train models by default.", url: "https://www.anthropic.com/privacy", label: "anthropic.com/privacy" },
            { name: "Giphy", desc: "GIF search in comments. Search queries and interaction data may be processed by Giphy.", url: "https://support.giphy.com/hc/en-us/articles/360032872931", label: "Giphy privacy policy" },
          ].map(({ name, desc, url, label }) => (
            <li key={name} style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, marginBottom: 6 }}>
              <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>{name}</strong> — {desc}{" "}
              <a href={url} target="_blank" rel="noopener noreferrer" style={{ color: "var(--page-text-primary)", textDecoration: "underline", textUnderlineOffset: 3 }}>{label}</a>
            </li>
          ))}
        </ul>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          We do not sell your data to any of these providers.
        </p>

        {/* Section 3 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          3. How We Use Your Information
        </h2>
        <ul style={{ margin: "8px 0 16px", paddingLeft: 20 }}>
          {["Create and maintain your account", "Display your profile and posts", "Power social features", "Send account emails", "Provide AI breakdown features", "Show content from followed creators", "Enable search and discovery", "Detect and prevent fraud and abuse", "Respond to support requests", "Improve the Platform", "Comply with applicable law"].map((item) => (
            <li key={item} style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, marginBottom: 6 }}>{item}</li>
          ))}
        </ul>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          We do not use your information for third-party advertising. FYTD does not currently run ads.
        </p>

        {/* Section 4 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          4. How We Share Your Information
        </h2>
        <h3 style={{ fontFamily: "var(--font-body)", fontSize: 14, fontWeight: 600, color: "var(--page-text-primary)", margin: "20px 0 8px", letterSpacing: "0.01em" }}>Public information (visible to all)</h3>
        <ul style={{ margin: "8px 0 16px", paddingLeft: 20 }}>
          {["Username, display name, profile avatar and bio", "Posts and fit breakdowns", "Follower and following counts", "Likes and saves counts"].map((i) => (
            <li key={i} style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, marginBottom: 6 }}>{i}</li>
          ))}
        </ul>
        <h3 style={{ fontFamily: "var(--font-body)", fontSize: 14, fontWeight: 600, color: "var(--page-text-primary)", margin: "20px 0 8px", letterSpacing: "0.01em" }}>Private information (only you or recipient)</h3>
        <ul style={{ margin: "8px 0 16px", paddingLeft: 20 }}>
          {["Email address", "Direct messages", "Blocked accounts list", "Notification history"].map((i) => (
            <li key={i} style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, marginBottom: 6 }}>{i}</li>
          ))}
        </ul>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>Service providers:</strong> shared only as necessary to operate the Platform.
        </p>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>Legal requirements:</strong> may disclose if required by law or valid legal process.
        </p>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          <strong style={{ color: "var(--page-text-primary)", fontWeight: 600 }}>Business transfers:</strong> if FYTD is acquired your information may transfer. You will be notified.
        </p>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          We do not sell your personal information.
        </p>

        {/* Section 5 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          5. Data Retention
        </h2>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          Retained while account is active. On account deletion: profile, posts, and public content removed; messages deleted; some data may remain in backups briefly before permanent deletion.
        </p>

        {/* Section 6 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          6. Children&apos;s Privacy (COPPA)
        </h2>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          FYTD is for users 13 and older. We do not knowingly collect data from children under 13. If you are under 13 do not use FYTD. If we discover we have data from a child under 13 we will delete it promptly. Contact: <a href="mailto:privacy@fytd.org" style={{ color: "var(--page-text-primary)", textDecoration: "underline", textUnderlineOffset: 3 }}>privacy@fytd.org</a>
        </p>

        {/* Section 7 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          7. Your Rights and Choices
        </h2>
        <ul style={{ margin: "8px 0 16px", paddingLeft: 20 }}>
          {["Account information: update anytime in settings.", "Account deletion: available through the Settings page.", "Washington State residents may have rights under the Washington My Health MY Data Act.", "California residents may have CCPA rights."].map((i) => (
            <li key={i} style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, marginBottom: 6 }}>{i}</li>
          ))}
        </ul>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          Contact <a href="mailto:privacy@fytd.org" style={{ color: "var(--page-text-primary)", textDecoration: "underline", textUnderlineOffset: 3 }}>privacy@fytd.org</a> to exercise rights.
        </p>

        {/* Section 8 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          8. Data Security
        </h2>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          Encrypted passwords, HTTPS for all data in transit, row-level security policies on database, regular security reviews. No method is 100% secure. Contact <a href="mailto:security@fytd.org" style={{ color: "var(--page-text-primary)", textDecoration: "underline", textUnderlineOffset: 3 }}>security@fytd.org</a> if your account is compromised.
        </p>

        {/* Section 9 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          9. Cookies
        </h2>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          FYTD uses essential cookies and local storage to keep you logged in, remember your theme preference, and maintain your session securely. No advertising or tracking cookies.
        </p>

        {/* Section 10 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          10. Third-Party Links
        </h2>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          Shop links in breakdowns go to third-party sites. We are not responsible for their privacy practices.
        </p>

        {/* Section 11 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          11. Changes to This Policy
        </h2>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          Material changes will be notified by an updated effective date and email for significant changes.
        </p>

        {/* Section 12 */}
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 500, color: "var(--page-text-primary)", letterSpacing: "-0.02em", margin: "36px 0 12px", paddingTop: 24, borderTop: "0.5px solid var(--page-border)" }}>
          12. Contact
        </h2>
        <ul style={{ margin: "8px 0 16px", paddingLeft: 20 }}>
          {[
            { label: "privacy@fytd.org", href: "mailto:privacy@fytd.org" },
            { label: "security@fytd.org", href: "mailto:security@fytd.org" },
            { label: "legal@fytd.org", href: "mailto:legal@fytd.org" },
          ].map(({ label, href }) => (
            <li key={label} style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, marginBottom: 6 }}>
              <a href={href} style={{ color: "var(--page-text-primary)", textDecoration: "underline", textUnderlineOffset: 3 }}>{label}</a>
            </li>
          ))}
        </ul>
        <p style={{ fontFamily: "var(--font-body)", fontSize: 14, color: "var(--page-text-secondary)", lineHeight: 1.7, margin: "0 0 14px" }}>
          fytd.org · Washington State, United States
        </p>
      </div>
    </div>
  );
}
